# Generated by Django 5.2.8 on 2025-11-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.JSONField()),
                ('duration_months', models.IntegerField()),
                ('product_id_ios', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id_android', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
