# Generated by Django 5.2.8 on 2025-12-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horsestatistic',
            unique_together={('horse', 'category', 'value')},
        ),
        migrations.RemoveField(
            model_name='horsestatistic',
            name='track',
        ),
    ]
