# Generated by Django 5.2.8 on 2025-12-02 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0002_alter_horsestatistic_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horsestatistic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='horsestatistic',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horse_race.track'),
        ),
        migrations.AlterUniqueTogether(
            name='horsestatistic',
            unique_together={('horse', 'category', 'value', 'track')},
        ),
    ]
