# Generated by Django 5.2.8 on 2025-12-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0003_alter_horsestatistic_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='predictorrating',
            name='horse_race__rating__fd98cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='predictorrating',
            name='horse_race__preset__0ab3a4_idx',
        ),
        migrations.RemoveField(
            model_name='predictorrating',
            name='rating_100',
        ),
    ]
