# Generated by Django 5.2.8 on 2025-12-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0004_remove_predictorrating_horse_race__rating__fd98cc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
