# Generated by Django 5.2.8 on 2025-12-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0005_track_track_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='gear_current',
            new_name='gear',
        ),
    ]
