# Generated by Django 5.2.8 on 2025-12-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0006_rename_gear_current_selection_gear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='silks_image',
        ),
    ]
