# Generated by Django 5.2.8 on 2025-12-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0007_remove_horse_silks_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='last_600_time',
        ),
        migrations.RemoveField(
            model_name='race',
            name='official_time',
        ),
    ]
