# Generated by Django 5.2.8 on 2025-12-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0008_remove_race_last_600_time_remove_race_official_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HorseRaceHistory',
        ),
    ]
