# Generated by Django 5.2.8 on 2025-12-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0009_delete_horseracehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='entry_conditions',
            field=models.JSONField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
