# Generated by Django 5.2.8 on 2025-12-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0010_alter_race_entry_conditions_alter_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
