# Generated by Django 5.2.8 on 2025-12-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0011_alter_meeting_meeting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='sprint_lane',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
