# Generated by Django 5.2.8 on 2025-12-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0012_alter_track_sprint_lane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='start_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
