# Generated by Django 5.2.8 on 2025-12-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0013_alter_race_start_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='claim',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
