# Generated by Django 5.2.8 on 2025-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0014_alter_selection_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='startTimeUtc_raw',
            field=models.CharField(blank=True, null=True),
        ),
    ]
