# Generated by Django 5.2.8 on 2025-12-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0015_meeting_starttimeutc_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='startTimeUtc_raw',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='weather',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='weather_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
