# Generated by Django 5.2.8 on 2025-12-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0016_race_starttimeutc_raw_race_weather_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='startTimeUtc_raw',
        ),
        migrations.RemoveField(
            model_name='race',
            name='weather',
        ),
        migrations.RemoveField(
            model_name='race',
            name='weather_rating',
        ),
    ]
