# Generated by Django 5.2.8 on 2025-12-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0017_remove_race_starttimeutc_raw_remove_race_weather_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='startTimeUtc_raw',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
