# Generated by Django 5.2.8 on 2025-12-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0018_race_starttimeutc_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
