# Generated by Django 5.2.8 on 2025-12-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0019_alter_race_number_alter_race_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='silks_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
