# Generated by Django 5.2.8 on 2025-12-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0020_alter_selection_silks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='track_condition',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='track_condition_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
