# Generated by Django 5.2.8 on 2025-12-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0021_alter_race_track_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='startTimeUtc_raw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='startTimeUtc_raw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
