# Generated by Django 5.2.8 on 2025-12-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0022_alter_meeting_starttimeutc_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='startTimeAus',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
