# Generated by Django 5.2.8 on 2025-12-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0023_race_starttimeaus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='startTimeAus',
        ),
    ]
