# Generated by Django 5.2.8 on 2025-12-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0024_remove_race_starttimeaus'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='startTimeUtcAus',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
