# Generated by Django 5.2.8 on 2026-01-01 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0025_race_starttimeutcaus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='last_10_starts',
        ),
    ]
