# Generated by Django 5.2.8 on 2026-01-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0026_remove_horse_last_10_starts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='in_running_positions',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='margin_decimal',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='result_label',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='result_position',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='starting_price',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='weight_carried',
        ),
    ]
