# Generated by Django 5.2.8 on 2026-01-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0027_remove_selection_in_running_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='in_running_positions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='selection',
            name='margin_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='result_label',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='selection',
            name='result_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='weight_carried',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
