# Generated by Django 5.2.8 on 2026-01-02 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0028_selection_in_running_positions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JockeyHorseStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('thirds', models.PositiveIntegerField(default=0)),
                ('win_percentage', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('place_percentage', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('roi', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('last_ten_starts', models.CharField(blank=True, max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse_race.horse')),
                ('jockey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse_race.jockey')),
            ],
            options={
                'indexes': [models.Index(fields=['horse', 'jockey'], name='horse_race__horse_i_31403f_idx'), models.Index(fields=['win_percentage'], name='horse_race__win_per_997dca_idx'), models.Index(fields=['place_percentage'], name='horse_race__place_p_ba3601_idx')],
                'unique_together': {('horse', 'jockey')},
            },
        ),
    ]
