# Generated by Django 5.2.8 on 2026-01-05 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0030_savedsearch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedsearch',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_saved_search'),
        ),
    ]
