# Generated by Django 5.2.8 on 2026-01-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0031_savedsearch_unique_saved_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='playup_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
