# Generated by Django 5.2.8 on 2026-01-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0032_meeting_playup_meeting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='playup_race_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='playup_fixed_odds_place',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='playup_fixed_odds_win',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='playup_price_fluctuations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='playup_selection_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
