# Generated by Django 5.2.8 on 2026-01-09 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0033_race_playup_race_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together={('meeting',)},
        ),
    ]
