# Generated by Django 5.2.8 on 2026-01-09 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0034_alter_selection_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together={('race', 'number')},
        ),
    ]
