# Generated by Django 5.2.8 on 2026-01-09 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0035_alter_selection_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together={('race', 'number', 'selectionId')},
        ),
    ]
