# Generated by Django 5.2.8 on 2026-01-09 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0038_alter_selection_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='race',
            unique_together={('meeting', 'number', 'raceId')},
        ),
    ]
