# Generated by Django 5.2.8 on 2025-11-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged_out',
            field=models.BooleanField(default=False),
        ),
    ]
